language: node_js
node_js:
- "6"
install:
- yarn global add typings tslint typescript
- typings i
- yarn
script:
- yarn run build
deploy:
  provider: npm
  email: zachbray@googlemail.com
  api_key: $NPM_KEY
  on:
    tags: true
